{{- $root := . -}}
{{- with .Values.imagePullSecrets }}
{{- with (first $root.Values.imagePullSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf " {\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\"}}}" $root.Values.imageCredentials.registry  $root.Values.imageCredentials.username  $root.Values.imageCredentials.password | b64enc }}
{{- end }}
{{- end }}
